import { CharacterName } from "../types/character";

export const CHARACTERS: CharacterName[] = [
  //Add in 2.2.0
  "Boothill",
  "Robin",
  "Trailblazer Girl (Imaginary)",
  "Trailblazer Boy (Imaginary)",
  //Add in 2.1.0
  "Aventurine",
  "Acheron",
  "Gallagher",
  //Add in 2.0.0
  "Sparkle",
  "Black Swan",
  "Misha",
  "Dr. Ratio",
  "Ruan Mei",
  "Xueyi",
  "Argenti",
  "Huohuo",
  "Jingliu",
  "Topaz & Numby",
  "Guinaifen",
  "Dan Heng • Imbibitor Lunae",
  "Fu Xuan",
  "Lynx",
  "Kafka",
  "Blade",
  "Luka",
  "Yukong",
  "Luocha",
  "Silver Wolf",
  "Arlan",
  "Asta",
  "Bailu",
  "Bronya",
  "Clara",
  "Dan Heng",
  "Gepard",
  "Herta",
  "Himeko",
  "Hook",
  "Jing Yuan",
  "March 7th",
  "Natasha",
  "Pela",
  "Qingque",
  "Sampo",
  "Seele",
  "Serval",
  "Sushang",
  "Tingyun",
  "Welt",
  "Yanqing",
  
  "Trailblazer Girl (Fire)",
  "Trailblazer Boy (Fire)",
  "Trailblazer Girl (Physical)",
  "Trailblazer Boy (Physical)",
];
