export const longStrings = {
  PublicCharDesc:
    "Para proteger a segurança e os direitos do usuário, atualizamos os dados da função hoyolab por meio do dispositivo do usuário (cliente) e não por meio do servidor. Isso significa que se um usuário não usar o Stargazer por um tempo, isso pode resultar em discrepâncias na contagem de personagens, dias ativos, conquistas alcançadas e dados do Salão Esquecido. Observe que esses dados são apenas para referência e não são precisos.",
  TrailblazerNotiTaggedU:
    'O jogador ${1} em "Discussão de ${2}" mencionou você! Venha participar da discussão.',
  UIDOnlySupportFullUID:
    "Suporta apenas pesquisa por UID completo, não é permitido pesquisar por nome ou UID parcial.",
  LoginViaPCToGetCookies:
    "Por favor, use um computador para fazer login no hoyolab. Certifique-se de sair e fazer login novamente e siga o vídeo de instruções: https://www.youtube.com/watch?v=CLkhV30kg_A (para copiar, selecione cURL (bash))",
  SelectServerAndPasteCookies:
    "Selecione o servidor e cole seus cookies.",
  CommentOverLimit:
    "O Comentário excede o limite máximo (200 caracteres), reduza o comentário antes de postar.",
  DonationRemoveAds: "Feito por Coding Band :D",
  AboutTheAppContent:
    "<h2>Sobre o Stargazer 2</h2><div>Stargazer 2 é um aplicativo assistente Star Rail de terceiros desenvolvido pela Coding Band. Ele fornece funções como consulta de proficiência, ilustração de personagem, consulta de desempenho, lista de classificação, etc... <br> Nosso objetivo é criar um aplicativo de Assistência Star Rail  com experiência móvel nativa para fornecer uma experiência de uso mais conveniente e tranquila.</ div><br><h2>Sobre a equipe</h2><div>Coding Band é uma equipe de desenvolvimento que se concentra no desenvolvimento da praticidade, mergulhando na arte e na diversão do software, e atualmente consiste em três membros principais:</div> <div><li>2O48: UI/UX Designer, revisor de arte </li><li>Dalufish: Engenheiro Chefe, desenvolvimento completo </li><li>Voc-夜芷冰：Gerente de Projeto, desenvolvimento completo </li></div><h2>Agradecimentos especiais</h2><div> Agradecimentos especiais a 明治 e a todos os testadores do beta fechado por nos ajudar a melhorar durante o período do beta fechado.<br>jedudu<br>yi_9487<br >appledush#0218<br>shiroweaver<br>_7475<br>rxin.66<br>rover5205<br>rudmon<br>.yanyi<br>mo_yc<br>ryouendragon3369<br>jonahs0202<br>mashujiu<br> yangyangxd<br>sava_tw<br>日輪#1577<br>.yangqin<br>sakura_snow.0w0<br>professionalwindowsexpert<br>dreamawake<br>_d_evil_<br>whitykun<br><br>Stargazer 2 não teria sido lançado em dois meses sem a sua ajuda :D</div><h2>Lembrete caloroso</h2><div>Observe que este projeto e aplicação não pertencem à miHoYo Co., Ltd. Stargazer 2 é apenas um projeto que fornece dados desenvolvidos por fãs. As informações fornecidas neste aplicativo são apenas para referência. Stargazer 2 não garante a exatidão e integridade de qualquer informação contida em qualquer grau. <br><br> Os direitos autorais de cada material usado no projeto 'Stargazer 2' pertencem ao detentor dos direitos autorais.<br> Os direitos autorais do código do projeto 'Stargazer 2' pertencem à Coding Band. </div><br> Alguns dos materiais utilizados neste projeto vêm dos seguintes sites <br>https://starrailstation.com/<br>https://github.com/reko-beep/hsr-data< br>https://honkai-star-rail.fandom.com/wiki/Honkai:_Star_Rail_Wiki<br>https://wiki.biligame.com/sr/首页<br>https://www.prydwen.gg/ star-rail<br>https://api.mihomo.me/<br>https://github.com/Mar-7th",
  IOSCantLoginYet:
    "Devido a limitações técnicas da plataforma iOS, atualmente o login só é possível através da utilização de cookies. Pedimos sinceras desculpas pelo transtorno causado >_<",
  LoginHint:
    "Observação: atualmente, o login em plataformas de terceiros não é compatível. Recomendamos que você vá para Configurações do jogo -> Configurações da conta -> Central do usuário -> Bind Pass para obter a melhor experiência.",
  LoginPolicy:
    "<p>Prezado usuário, o login na função da conta Hoyoverse requer que seus cookies sejam armazenados no dispositivo, portanto, devemos obter sua autorização antes de prosseguir. Garantimos que seus cookies serão salvos apenas localmente e usados apenas entre você e a Hoyoverse. Além disso, também armazenaremos dados de jogos (mas não cookies) no servidor para fornecer serviços (como classificação MDC).</p><br/><p>Observação: primeiro, não podemos obter as informações de conta e senha. A inserção da senha da conta é utilizada apenas para fornecer uma forma mais conveniente de obter cookies, substituindo a inconveniência de pesquisar e inserir cookies manualmente. Em segundo lugar, garantimos que os cookies são armazenados apenas no dispositivo do utilizador (cliente) (seja obtido manualmente ou através da página de login). Você pode visualizar o código-fonte relevante no repositório GitHub da Stargazer para verificar esta mensagem. Portanto, não seremos responsáveis pelo roubo da senha da conta de qualquer usuário.",
    GithubStarPlease: "Se você acha que este projeto é útil, dê-nos uma estrela no GitHub, obrigado!",

  };
